// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwrpdhvfbuwhqoxpkeui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3cnBkaHZmYnV3aHFveHBrZXVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMDk0NzAsImV4cCI6MjA2NjU4NTQ3MH0._NfXbITHUQXHTKQa63bDTIY5PnH5dbpFZEoC-uBCKD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);